<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\User;
use App\Models\Brand;
use App\Models\Device;
use App\Models\Driver;
use App\Models\OperationSystem;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::insert([
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('admin888'),
                'is_active' => 1,
            ]
        ]);

        Device::insert([
            ['name' => 'Printer'],
            ['name' => 'Scanner'],
            ['name' => 'Network Adapter'],
            ['name' => 'Webcam'],
            ['name' => 'Audio Interface'],
        ]);

        Brand::insert([
             ['name' => 'HP'],
            ['name' => 'Canon'],
            ['name' => 'Epson'],
            ['name' => 'Brother'],
            ['name' => 'Logitech'],
            ['name' => 'Samsung'],
            ['name' => 'Dell'],
            ['name' => 'Lenovo'],
            ['name' => 'Asus'],
            ['name' => 'Acer'],
            ['name' => 'Microsoft'],
            ['name' => 'Apple'],
            ['name' => 'Xerox'],
            ['name' => 'Fujitsu'],
            ['name' => 'Panasonic'],
            ['name' => 'Toshiba'],
            ['name' => 'Sharp'],
            ['name' => 'Ricoh'],
            ['name' => 'Kyocera'],
            ['name' => 'Zebra'],
            ['name' => 'Lexmark'],
            ['name' => 'OKI'],
            ['name' => 'BenQ'],
            ['name' => 'Razer'],
            ['name' => 'SteelSeries'],
            ['name' => 'Corsair'],
            ['name' => 'MSI'],
            ['name' => 'Gigabyte'],
            ['name' => 'Intel'],
            ['name' => 'AMD'],
            ['name' => 'NVIDIA'],
            ['name' => 'Realtek'],
            ['name' => 'TP-Link'],
            ['name' => 'D-Link'],
            ['name' => 'Netgear'],
            ['name' => 'Ubiquiti'],
            ['name' => 'Cisco'],
            ['name' => 'Synology'],
            ['name' => 'QNAP'],
            ['name' => 'Western Digital'],
            ['name' => 'Seagate'],
            ['name' => 'Targus'],
            ['name' => 'Anker'],
            ['name' => 'Sandisk'],
            ['name' => 'Kingston'],
            ['name' => 'Crucial'],
            ['name' => 'ADATA'],
            ['name' => 'Transcend'],
            ['name' => 'Verbatim'],
            ['name' => 'ViewSonic'],
            ['name' => 'Philips'],
            ['name' => 'LG'],
            ['name' => 'Sony'],
            ['name' => 'JBL'],
            ['name' => 'Bose'],
            ['name' => 'Beats'],
            ['name' => 'Harman Kardon'],
            ['name' => 'Sennheiser'],
            ['name' => 'Plantronics'],
            ['name' => 'Poly'],
            ['name' => 'HyperX'],
            ['name' => 'Creative'],
            ['name' => 'AOC'],
            ['name' => 'Alienware'],
            ['name' => 'Roccat'],
            ['name' => 'Thrustmaster'],
            ['name' => 'Elgato'],
            ['name' => 'NZXT'],
            ['name' => 'Noctua'],
            ['name' => 'Cooler Master'],
            ['name' => 'Thermaltake'],
            ['name' => 'Arctic'],
            ['name' => 'Zalman'],
            ['name' => 'iBUYPOWER'],
            ['name' => 'CyberPowerPC'],
            ['name' => 'ORICO'],
            ['name' => 'IOGEAR'],
            ['name' => 'Kensington'],
            ['name' => 'Belkin'],
            ['name' => 'TRENDnet'],
            ['name' => 'Avaya'],
            ['name' => 'Logisys'],
            ['name' => 'EVGA'],
            ['name' => 'XFX'],
            ['name' => 'Foxconn'],
            ['name' => 'ASRock'],
            ['name' => 'BIOSTAR'],
            ['name' => 'Rosewill'],
            ['name' => 'Enermax'],
            ['name' => 'Be Quiet!'],
            ['name' => 'Fractal Design'],
            ['name' => 'Lian Li'],
            ['name' => 'In Win'],
            ['name' => 'SilverStone'],
            ['name' => 'Monoprice'],
            ['name' => 'Vizio'],
            ['name' => 'Hisense'],
            ['name' => 'Haier'],
            ['name' => 'Pioneer'],
            ['name' => 'Onkyo'],
            ['name' => 'Denon'],
            ['name' => 'Marantz'],
            ['name' => 'Yamaha'],
        ]);

        OperationSystem::insert([
            ['name' => 'Windows 11'],
            ['name' => 'Windows 10'],
            ['name' => 'Windows 8.1'],
            ['name' => 'Windows 7'],
            ['name' => 'Windows XP'],
            ['name' => 'Windows Vista'],
            ['name' => 'Windows Server 2022'],
            ['name' => 'Windows Server 2019'],
            ['name' => 'Windows Server 2016'],
            ['name' => 'Windows Server 2012 R2'],
            ['name' => 'Windows Server 2008 R2'],
            ['name' => 'Windows Embedded'],
            ['name' => 'macOS Sonoma'],
            ['name' => 'macOS Ventura'],
            ['name' => 'macOS Monterey'],
            ['name' => 'macOS Big Sur'],
            ['name' => 'macOS Catalina'],
            ['name' => 'macOS Mojave'],
            ['name' => 'macOS High Sierra'],
            ['name' => 'Ubuntu 24.04 LTS'],
            ['name' => 'Ubuntu 22.04 LTS'],
            ['name' => 'Ubuntu 20.04 LTS'],
            ['name' => 'Debian 12'],
            ['name' => 'Debian 11'],
            ['name' => 'Fedora 40'],
            ['name' => 'Fedora 39'],
            ['name' => 'Arch Linux'],
            ['name' => 'Linux Mint'],
            ['name' => 'Zorin OS'],
            ['name' => 'Manjaro'],
            ['name' => 'elementary OS'],
            ['name' => 'Kali Linux'],
            ['name' => 'CentOS 7'],
            ['name' => 'Red Hat Enterprise Linux 9'],
            ['name' => 'Red Hat Enterprise Linux 8'],
            ['name' => 'Oracle Linux'],
            ['name' => 'Android 14'],
            ['name' => 'Android 13'],
            ['name' => 'Android 12'],
            ['name' => 'Android 11'],
            ['name' => 'Android 10'],
            ['name' => 'iOS 17'],
            ['name' => 'iOS 16'],
            ['name' => 'iOS 15'],
            ['name' => 'Chrome OS'],
            ['name' => 'FreeBSD'],
            ['name' => 'OpenBSD'],
            ['name' => 'ReactOS'],
            ['name' => 'Haiku OS'],
            ['name' => 'Tails'],
        ]);

        Driver::insert([
            [
                'device_id' => 1,
                'brand_id' => 3, // Epson
                'operation_system_id' => 1, // Windows 11
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3150 Web-Installer (Windows)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Ink-Tank-Printers/L-Series/Epson-EcoTank-L3150/s/SPT_C11CG86501',
                'status' => 'active',
                'notes' => 'Web installer for Windows 10/11 32/64-bit',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 2, // Windows 10
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3150 Web-Installer (Mac)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Ink-Tank-Printers/L-Series/Epson-EcoTank-L3150/s/SPT_C11CG86501?review-filter=Mac+OS+X+10.11.x',
                'status' => 'active',
                'notes' => 'Installer for Mac OS X 10.11 and above',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 1,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3250 Web-Installer (Windows)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Ink-Tank-Printers/L-Series/Epson-EcoTank-L3250/s/SPT_C11CJ67503',
                'status' => 'active',
                'notes' => 'Web installer for L3250 on Windows',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 3, // macOS
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3250 Web-Installer (Mac)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Ink-Tank-Printers/L-Series/Epson-EcoTank-L3250/s/SPT_C11CJ67503?review-filter=Mac+OS+X+11.x',
                'status' => 'active',
                'notes' => 'Web installer for L3250 on macOS',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 1,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson WorkForce WF-2830 Driver & Utilities (Windows)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/scansmart',
                'status' => 'active',
                'notes' => 'Use Epson ScanSmart for Windows',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 3,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson WorkForce WF-2830 Driver & Utilities (Mac)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/scansmart',
                'status' => 'active',
                'notes' => 'Epson ScanSmart also available for macOS',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 1,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3110 Driver (Windows)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Support/Printers/All-In-One/L-Series/Epson-L3150/s/SPT_C11CG86504',
                'status' => 'active',
                'notes' => 'Driver for L3110 on Windows',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 3,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3110 Driver (Mac)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id/Support/Printers/All-In-One/L-Series/Epson-L3150/s/SPT_C11CG86504',
                'status' => 'active',
                'notes' => 'Driver for L3110 on macOS',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 1,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3156 Driver (Windows)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id',
                'status' => 'active',
                'notes' => 'L3156 Windows web installer',
            ],
            [
                'device_id' => 1,
                'brand_id' => 3,
                'operation_system_id' => 3,
                'architecture' => '64bit',
                'serial_number' => null,
                'name' => 'Epson EcoTank L3156 Driver (Mac)',
                'version' => null,
                'download_url' => 'https://www.epson.co.id',
                'status' => 'active',
                'notes' => 'L3156 Mac web installer',
            ],
        ]);
    }
}
